# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 20:48
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CraigsListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(blank=True, null=True)),
                ('ts_imported', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('city_code', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('url', models.URLField(blank=True, db_index=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='$ in cents')),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
